version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly
  tests: false

linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - unused
    - goconst
    - gocyclo
    - ineffassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
