// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	domain "avito-tech-go-task/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// FindByName mocks base method.
func (m *MockTeamRepository) FindByName(ctx context.Context, teamName string) (*domain.Team, []*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, teamName)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].([]*domain.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByName indicates an expected call of FindByName.
func (mr *MockTeamRepositoryMockRecorder) FindByName(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockTeamRepository)(nil).FindByName), ctx, teamName)
}

// Save mocks base method.
func (m *MockTeamRepository) Save(ctx context.Context, team *domain.Team, teamMembers []*domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, team, teamMembers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTeamRepositoryMockRecorder) Save(ctx, team, teamMembers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTeamRepository)(nil).Save), ctx, team, teamMembers)
}

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockPullRequestRepository) DeleteByID(ctx context.Context, prID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, prID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPullRequestRepositoryMockRecorder) DeleteByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPullRequestRepository)(nil).DeleteByID), ctx, prID)
}

// FindByID mocks base method.
func (m *MockPullRequestRepository) FindByID(ctx context.Context, prID string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, prID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPullRequestRepositoryMockRecorder) FindByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByID), ctx, prID)
}

// FindByReviewerID mocks base method.
func (m *MockPullRequestRepository) FindByReviewerID(ctx context.Context, reviewerID string) ([]*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByReviewerID", ctx, reviewerID)
	ret0, _ := ret[0].([]*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByReviewerID indicates an expected call of FindByReviewerID.
func (mr *MockPullRequestRepositoryMockRecorder) FindByReviewerID(ctx, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByReviewerID", reflect.TypeOf((*MockPullRequestRepository)(nil).FindByReviewerID), ctx, reviewerID)
}

// Save mocks base method.
func (m *MockPullRequestRepository) Save(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPullRequestRepositoryMockRecorder) Save(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPullRequestRepository)(nil).Save), ctx, pr)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindActiveUserIDsByTeam mocks base method.
func (m *MockUserRepository) FindActiveUserIDsByTeam(ctx context.Context, team string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveUserIDsByTeam", ctx, team)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveUserIDsByTeam indicates an expected call of FindActiveUserIDsByTeam.
func (mr *MockUserRepositoryMockRecorder) FindActiveUserIDsByTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveUserIDsByTeam", reflect.TypeOf((*MockUserRepository)(nil).FindActiveUserIDsByTeam), ctx, team)
}

// FindActiveUserIDsByTeamExcludeAuthor mocks base method.
func (m *MockUserRepository) FindActiveUserIDsByTeamExcludeAuthor(ctx context.Context, team, excludeAuthorID string, reviewersCount int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveUserIDsByTeamExcludeAuthor", ctx, team, excludeAuthorID, reviewersCount)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveUserIDsByTeamExcludeAuthor indicates an expected call of FindActiveUserIDsByTeamExcludeAuthor.
func (mr *MockUserRepositoryMockRecorder) FindActiveUserIDsByTeamExcludeAuthor(ctx, team, excludeAuthorID, reviewersCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveUserIDsByTeamExcludeAuthor", reflect.TypeOf((*MockUserRepository)(nil).FindActiveUserIDsByTeamExcludeAuthor), ctx, team, excludeAuthorID, reviewersCount)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, userID)
}

// FindTeamByUserID mocks base method.
func (m *MockUserRepository) FindTeamByUserID(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTeamByUserID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTeamByUserID indicates an expected call of FindTeamByUserID.
func (mr *MockUserRepositoryMockRecorder) FindTeamByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTeamByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindTeamByUserID), ctx, userID)
}

// Save mocks base method.
func (m *MockUserRepository) Save(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryMockRecorder) Save(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepository)(nil).Save), ctx, user)
}

// SetIsActive mocks base method.
func (m *MockUserRepository) SetIsActive(ctx context.Context, userID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserRepositoryMockRecorder) SetIsActive(ctx, userID, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserRepository)(nil).SetIsActive), ctx, userID, isActive)
}
